##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  archlinux:
    # Useful URL: https://git.archlinux.org/svntogit/community.git/tree/mate-calc
    - autoconf-archive
    - clang
    - gcc
    - git
    - gtk3
    - intltool
    - make
    - mate-common
    - which
    - yelp-tools

  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/mate-calc
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - gcc
    - git
    - libatk1.0-dev
    - libglib2.0-dev
    - libgmp-dev
    - libgtk-3-dev
    - libmpc-dev
    - libmpfr-dev
    - libxml2-dev
    - make
    - mate-common
    - yelp-tools

  fedora:
    # Useful URL: https://src.fedoraproject.org/cgit/rpms/mate-calc.git
    - autoconf-archive
    - clang
    - clang-analyzer
    - bison
    - desktop-file-utils
    - flex
    - gcc
    - git
    - gmp-devel
    - gtk3
    - libmpc-devel
    - libxml2-devel
    - make
    - mate-common
    - mate-desktop-devel
    - mpfr-devel
    - redhat-rpm-config

  ubuntu:
    - autopoint
    - clang
    - clang-tools
    - gcc
    - git
    - libatk1.0-dev
    - libglib2.0-dev
    - libgmp-dev
    - libgtk-3-dev
    - libmpc-dev
    - libmpfr-dev
    - libxml2-dev
    - make
    - mate-common
    - yelp-tools

variables:
  - 'CHECKERS="
    -enable-checker deadcode.DeadStores
    -enable-checker alpha.deadcode.UnreachableCode
    -enable-checker alpha.core.CastSize
    -enable-checker alpha.core.CastToStruct
    -enable-checker alpha.core.IdenticalExpr
    -enable-checker alpha.core.SizeofPtr
    -enable-checker alpha.security.ArrayBoundV2
    -enable-checker alpha.security.MallocOverflow
    -enable-checker alpha.security.ReturnPtrRange
    -enable-checker alpha.unix.SimpleStream
    -enable-checker alpha.unix.cstring.BufferOverlap
    -enable-checker alpha.unix.cstring.NotNullTerminated
    -enable-checker alpha.unix.cstring.OutOfBounds
    -enable-checker alpha.core.FixedAddr
    -enable-checker security.insecureAPI.strcpy"'

before_scripts:

build_scripts:
  - NOCONFIGURE=1 ./autogen.sh
  - scan-build $CHECKERS ./configure
  - if [ $CPU_COUNT -gt 1 ]; then
  -     scan-build $CHECKERS --keep-cc -o html-report make -j $CPU_COUNT
  - else
  -     scan-build $CHECKERS --keep-cc -o html-report make
  - fi
  - if [ ${DISTRO_NAME} == "debian" ];then
  -     cppcheck --enable=warning,style,performance,portability,information,missingInclude .
  - fi


after_scripts:
  - make distcheck

releases:
  draft: false
  prerelease: false
  checksum: true
  file_glob: true
  files: mate-calc-*.tar.xz
  github_release:
    tags: true
    overwrite: true
    base_version: 1.20.0
    notify_servers:
      - https://release.mate-desktop.org/release

