.\" Copyright (c) 2011 Jean Schurger
.TH MATE-CALC-CMD 1 "17 March 2011"
.SH NAME
mate-calc-cmd \- a console calculator
.SH SYNOPSIS
.B mate-calc-cmd

.SH DESCRIPTION
.B mate-calc-cmd
is the console version of
.B mate-calc
the calculator of the MATE desktop environment.

.SH SEE ALSO
.B mate-calc
.sp
.LP
