.\" Copyright (c) 2011 Jean Schurger
.\" Man page for mate-calc
.TH MATE-CALC-CMD 1 "1 February 2014" "MATE Desktop Environment" "General Manual"
.\" Please adjust this date when revising the manpage.
.\"
.SH "NAME"
mate-calc-cmd \- A console calculator for the MATE Desktop Environment.
.SH "SYNOPSIS"
\fBmate-calc-cmd\fR
.SH "DESCRIPTION"
\fBmate-calc-cmd\fR is the console version of \fBmate-calc\fR, the calculator for the MATE Desktop Environment.
.SH "BUGS"
.SS Should you encounter any bugs, they may be reported at: 
http://github.com/mate-desktop/mate-calc/issues
.SH "SEE ALSO"
.SS Further information may also be available at: http://wiki.mate-desktop.org/docs
.P
.BR mate-calc (1)
